[package]
name = "darkbtc"
version = "0.1.0"
edition = "2024_07"

[[target.starknet-contract]]
sierra = true
casm = true

[dependencies]
starknet = "2.11.4"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", rev = "f1c15a30a44311166e0368081c5f79ab5a02c1d3" }

[dev-dependencies]
snforge_std = "0.44.0"

[scripts]
test = "snforge test"
build = "scarb build"
